#!/bin/bash
#SBATCH --job-name=CnR_setab_MO		                        # Job name
#SBATCH --partition=batch		                            # Partition (queue) name
#SBATCH --ntasks=1	                                # Single task job
#SBATCH --cpus-per-task=24		                            # Number of cores per task - match this to the num_threads used by BLAST
#SBATCH --mem=40gb			                                # Total memory for job
#SBATCH --time=48:00:00  		                            # Time limit hrs:min:sec
#SBATCH --output=/scratch/ara67776/CnR_setAB			    # Location of standard output and error log files (replace cbergman with your myid)
#SBATCH --mail-user=ara67776@uga.edu                    # Where to send mail (replace cbergman with your myid)
#SBATCH --mail-type=ALL                            # Mail events (BEGIN, END, FAIL, ALL)
#SBATCH --output=/home/ara67776/work/error/log.%j			    # Location of standard output and error log files (replace cbergman with your myid)

#set output directory
OUTDIR="/scratch/ara67776/CnR_timecourse"

##start with trimming raw reads##
ml Trim_Galore
#starting with raw files in $OUTDIR/raw
#mkdir $OUTDIR/trimmed
trim_galore --fastqc -j 8 --output_dir $OUTDIR/trimmed --paired $OUTDIR/raw/CnR_timecourse_K9_2_to_4h/24hpf_IgG_R1.fastq.gz $OUTDIR/raw/CnR_timecourse_K9_2_to_4h/24hpf_IgG_R2.fastq.gz
trim_galore --fastqc -j 8 --output_dir $OUTDIR/trimmed --paired $OUTDIR/raw/CnR_timecourse_K9_2_to_4h/24hpf_K9_1_R1.fastq.gz $OUTDIR/raw/CnR_timecourse_K9_2_to_4h/24hpf_K9_1_R2.fastq.gz
trim_galore --fastqc -j 8 --output_dir $OUTDIR/trimmed --paired $OUTDIR/raw/CnR_timecourse_K9_2_to_4h/24hpf_K9_2_R1.fastq.gz $OUTDIR/raw/CnR_timecourse_K9_2_to_4h/24hpf_K9_2_R2.fastq.gz
trim_galore --fastqc -j 8 --output_dir $OUTDIR/trimmed --paired $OUTDIR/raw/CnR_timecourse_K9_2_to_4h/24hpf_K9_3_R1.fastq.gz $OUTDIR/raw/CnR_timecourse_K9_2_to_4h/24hpf_K9_3_R2.fastq.gz
trim_galore --fastqc -j 8 --output_dir $OUTDIR/trimmed --paired $OUTDIR/raw/CnR_timecourse_K9_2_to_4h/2.5hpf_IgG_1_R1.fastq.gz $OUTDIR/raw/CnR_timecourse_K9_2_to_4h/2.5hpf_IgG_1_R2.fastq.gz
trim_galore --fastqc -j 8 --output_dir $OUTDIR/trimmed --paired $OUTDIR/raw/CnR_timecourse_K9_2_to_4h/2.5hpf_K9_1_R1.fastq.gz $OUTDIR/raw/CnR_timecourse_K9_2_to_4h/2.5hpf_K9_1_R2.fastq.gz
trim_galore --fastqc -j 8 --output_dir $OUTDIR/trimmed --paired $OUTDIR/raw/CnR_timecourse_K9_2_to_4h/2.5hpf_K9_2_R1.fastq.gz $OUTDIR/raw/CnR_timecourse_K9_2_to_4h/2.5hpf_K9_2_R2.fastq.gz
trim_galore --fastqc -j 8 --output_dir $OUTDIR/trimmed --paired $OUTDIR/raw/CnR_timecourse_K9_2_to_4h/2.5hpf_K9_3_R1.fastq.gz $OUTDIR/raw/CnR_timecourse_K9_2_to_4h/2.5hpf_K9_3_R2.fastq.gz
trim_galore --fastqc -j 8 --output_dir $OUTDIR/trimmed --paired $OUTDIR/raw/CnR_timecourse_K9_2_to_4h/4.5hpf_IgG_1_R1.fastq.gz $OUTDIR/raw/CnR_timecourse_K9_2_to_4h/4.5hpf_IgG_1_R2.fastq.gz
trim_galore --fastqc -j 8 --output_dir $OUTDIR/trimmed --paired $OUTDIR/raw/CnR_timecourse_K9_2_to_4h/4.5hpf_K9_1_R1.fastq.gz $OUTDIR/raw/CnR_timecourse_K9_2_to_4h/4.5hpf_K9_1_R2.fastq.gz
trim_galore --fastqc -j 8 --output_dir $OUTDIR/trimmed --paired $OUTDIR/raw/CnR_timecourse_K9_2_to_4h/4.5hpf_K9_2_R1.fastq.gz $OUTDIR/raw/CnR_timecourse_K9_2_to_4h/4.5hpf_K9_2_R2.fastq.gz
trim_galore --fastqc -j 8 --output_dir $OUTDIR/trimmed --paired $OUTDIR/raw/CnR_timecourse_K9_2_to_4h/4.5hpf_K9_3_R1.fastq.gz $OUTDIR/raw/CnR_timecourse_K9_2_to_4h/4.5hpf_K9_3_R2.fastq.gz
